### ISSUE TITLE
Get disk space in crontab fails

### ISSUE THREAD

**Issue by saramonzon** [BU-ISCIII/iSkyLIMS_wetlab#10]
Traceback (most recent call last):                                                                                          
  File "/srv/iSkyLIMS/virtualenv/lib/python3.6/site-packages/django_crontab/crontab.py", line 145, in run_job               
    func(*job_args, **job_kwargs)                                                                                           
  File "/srv/iSkyLIMS/wetlab/cron.py", line 72, in check_not_finish_run                                                     
    updated_run=find_not_completed_run(logger)                                                                              
  File "/srv/iSkyLIMS/wetlab/utils/parsing_run_info.py", line 1052, in find_not_completed_run                               
    processed_run[state]=process_run_in_bcl2F_q_executed_state(working_list['Bcl2Fastq Executed'], logger)                  
  File "/srv/iSkyLIMS/wetlab/utils/parsing_run_info.py", line 995, in process_run_in_bcl2F_q_executed_state
    get_run_disk_utilization (conn, run_Id_used, run_processing_id, logger)
  File "/srv/iSkyLIMS/wetlab/utils/parsing_run_info.py", line 69, in get_run_disk_utilization
    item_dir = os.path.join(run_name, item_list.filename)
NameError: name 'run_name' is not defined

**Comment by luissian** [comment]
wrong variable used when looking for the run directory. 
the variable "run_Id_used" must be used instead 
Corrected, pending to verify
